# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lib_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
